name: event-detection-transformation
language: Python
variables:
  - name: input
    inputType: InputTopic
    defaultValue: f1-data
  - name: output
    inputType: OutputTopic
    defaultValue: hard-braking
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: quix_function.py
libraryItemId: event-detection-transformation
